Autonomous
Team1710CTO/Team1710-2022-Robot-Code pull request #5
Opened 2022-02-11 00:15 UTC by Andrew-K961

Rotation doesn't work yet but this removes the SDS library and makes it a dependency. Also makes calibration easier by reorganizing the Constants file.

2022-02-12 14:29 UTC, Team1710CTO requested changes
RIP heading control. plz don't remove it. Since there are so many changes to the SDS lib(although deleting unnecessary files will help compilations go faster) I would like you to test and see that all the base functions of the drivetrain work before we push this to master.

2022-02-12 14:29 UTC, Team1710CTO commented on src/main/java/frc/robot/RobotContainer.java
> +            .whenPressed(m_drivetrainSubsystem::resetFieldOriented)
make sure to bind setIsZeroingFalse to when released otherwise the heading control wont reactivate

2022-02-12 14:29 UTC, Team1710CTO commented on src/main/java/frc/robot/RobotContainer.java
> +    return new autonomousCommand(m_drivetrainSubsystem);
yay auto

2022-02-12 14:29 UTC, Team1710CTO commented on src/main/java/frc/robot/subsystems/DrivetrainSubsystem.java
> +		SmartDashboard.putNumber("Pigeon Y", xyz[1]);
Make sure the branch you're requesting to pull is up to date with the latest master changes. These changes are removing heading control.

2022-02-12 14:30 UTC, Team1710CTO commented on src/main/java/frc/robot/subsystems/DrivetrainSubsystem.java
> +		SmartDashboard.putNumber("Pigeon Y", xyz[1]);
My B I pointed this comment to the wrong line.

2022-02-14 23:44 UTC, Andrew-K961 commented
Heading control back and ready to merge

2022-03-07 14:34 UTC, closed without merging